// loop-performance/react-loop-performance/src/components/SimpleGrid/SimpleGrid.tsx
import './SimpleGrid.scss';
import { useState } from 'react';
import { useAppSelector } from '../../store';
import { selectGridData } from '../../store/loopPageSelectors';
import SimpleGridActions from '../SimpleGridActions/SimpleGridActions';
import SimpleGridRows from '../SimpleGridRows/SimpleGridRows';

function SimpleGrid() {
  const gridData = useAppSelector(selectGridData);
  const [showHeader, setShowHeader] = useState(true);

  return (
    <section>
      <SimpleGridActions showHeader={showHeader} setShowHeader={setShowHeader} />
      <ul className="grid">
        {showHeader && (
          <li className="grid-row grid-row-header">
            <div className="grid-data-id">ID</div>
            <div className="grid-data-caption">Caption</div>
            <div className="grid-data-quantity">Quantity</div>
          </li>
        )}
        <SimpleGridRows gridData={gridData} />
      </ul>
    </section>
  );
}

export default SimpleGrid;

// loop-performance/angular-loop-performance/src/components/simple-grid/simple-grid.ts
import { Component, inject, signal } from '@angular/core';
import { SimpleGridActions } from '../simple-grid-actions/simple-grid-actions';
import { Store } from '@ngrx/store';
import { selectGridData } from '../../store/loopPageSelectors';
import { AsyncPipe } from '@angular/common';

@Component({
  imports: [SimpleGridActions, AsyncPipe],
  selector: 'alp-simple-grid',
  styleUrl: './simple-grid.scss',
  templateUrl: './simple-grid.html',
})
export class SimpleGrid {
  private store = inject(Store);
  showHeader = signal(true);
  gridData = this.store.select(selectGridData);
}
