// loop-performance/react-loop-performance/src/components/SimpleCounter/SimpleCounter.tsx
import { useAppDispatch, useAppSelector } from '../../store';
import { incrementCounterAction } from '../../store/loopPageActions';
import { selectCounter } from '../../store/loopPageSelectors';
import './SimpleCounter.scss';

function SimpleCounter() {
  const counter = useAppSelector(selectCounter);
  const dispatch = useAppDispatch();
  return (
    <section className="simple-counter">
      <button onClick={() => dispatch(incrementCounterAction())}>Increment</button>
      <div className="simple-counter-value">{counter}</div>
    </section>
  );
}

export default SimpleCounter;

// loop-performance/angular-loop-performance/src/components/simple-counter/simple-counter.ts
import { Component, inject } from '@angular/core';
import { Store } from '@ngrx/store';
import { selectCounter } from '../../store/loopPageSelectors';
import { AsyncPipe } from '@angular/common';
import { incrementCounterAction } from '../../store/loopPageActions';

@Component({
  imports: [AsyncPipe],
  selector: 'alp-simple-counter',
  styleUrl: './simple-counter.scss',
  templateUrl: './simple-counter.html',
})
export class SimpleCounter {
  private store = inject(Store);
  counter = this.store.select(selectCounter);

  increment() {
    this.store.dispatch(incrementCounterAction());
  }
}
